# Lorentz Invariance of the Dirac Equation
Since we derived the Dirac equation using a relativistic relationship,
it should remain invariant under Lorentz transformations, i.e. boosts and
rotations. Let's act agnostic to the fact that $\psi$ is not a four-vector,
and instead say there exists some matrix $S$ that transforms $\psi$ under
Lorentz transformations,
$$
\psi\to \psi' = S\psi.
$$
Note that $S$ must be some $4\times 4$ matrix for $\psi$ to maintain its
form as a column matrix with four entries. Recall that four-vectors transform
according to 
$$
r'^\mu = {\Lambda^\mu}_\nu r^\nu
$$
where ${\Lambda^\mu}_\nu$ is the standard Lorentz transformation matrix. For
boosts in the $r^1 = x$ direction, $\Lambda$ takes the form
$$
\begin{equation}
\Lambda = 
\begin{pmatrix}
\gamma & -\gamma\beta & 0 & 0 \\
-\gamma\beta & \gamma & 0 & 0 \\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}
\end{equation}
$$
yielding
$$
ct' = \gamma (ct - \beta x), \qquad
x' = \gamma (x - \beta ct), \qquad
y' = y, \qquad
z' = z.
$$
If $\psi$ were a four-vector, then $S = \Lambda$. We will see, however,
that this is not the case. First, we apply a Lorentz transformation to the
Dirac equation assuming that $S$ is the matrix that transforms $\psi$. Since
$\partial_\mu$ is covariant,
$$
\partial'_\mu = {(\Lambda^{-1})^\nu}_\mu \partial_\nu
$$
Putting all this into the Dirac equation gives us
$$
i\hbar S^{-1}\gamma^\mu S {(\Lambda^{-1})^\nu}_\mu\partial_\nu\psi - 
mc\psi = 0.
$$
In order for the Dirac equation to be Lorentz invariant, then, the following
relation must hold.
$$
S^{-1}\gamma^\mu S {(\Lambda^{-1})^\nu}_\mu = \gamma^\nu
$$
or, acting from the right with $\Lambda$,
$$
S^{-1}\gamma^\mu S = {\Lambda^\mu}_\nu\gamma^\nu.
$$
The way we find the relationship between $S$ and $\Lambda$ is by working
with infinitesimal transformations and then building up to finite 
transformations. We take the infinitesimal form of $\Lambda$ to be
$$
{\Lambda^\mu}_\nu \approx {\delta^\mu}_\nu + {\omega^\mu}_\nu,
$$
where we define the Kronecker delta
$$
{\delta^\mu}_\nu =
\begin{cases}
1, \qquad \mu = \nu\\
0, \qquad \mu \ne \nu
\end{cases}
$$
and ${\omega^\mu}_\nu$ is some $4\times 4$ matrix. The defining quality of
the Lorentz transformation is that it leaves the Minkowski spacetime metric
invariant,
$$
{\Lambda^\mu}_\rho {\Lambda^\nu}_\sigma \eta^{\rho\sigma} = \eta^{\mu\nu}.
$$
Substituting the infinitesimal form of $\Lambda$ into this equation results
in the constraint that
$$
\omega^{\mu\nu} + \omega^{\nu\mu} = 0.
$$
Note that this antisymmetry applies when both indices are upper or
lower, but not when the indices are mixed upper and lower. We can use Kronecker
deltas and $\eta^{\mu\nu}$ to get
$$
{\omega^\mu}_\nu = \frac{1}{2}\omega_{\rho\sigma}
(\eta^{\mu\rho}{\delta^\sigma}_\nu - \eta^{\mu\sigma}{\delta^\rho}_\nu)
$$
where we took advantage of the antisymmetry of $\omega_{\rho\sigma}$. We
define the matrix in parentheses as
$$
{(M^{\rho\sigma})^\mu}_\nu = \eta^{\mu\rho}{\delta^\sigma}_\nu - 
\eta^{\mu\sigma}{\delta^\rho}_\nu.
$$
If we raise the $\nu$ index, we find that this matrix is antisymmetric in both
$\mu\nu$ and $\rho\sigma$,
$$
(M^{\rho\sigma})^{\mu\nu} =
\eta^{\mu\rho}\eta^{\sigma\nu} - \eta^{\nu\rho}\eta^{\mu\sigma}
$$
Thus, $(M^{\rho\sigma})^{\mu\nu}$ represents 6 different matrices (denoted by
the pair $\rho\sigma$) which are $4\times 4$ whose matrix elements are denoted
by the pair $\mu\nu$. When contracted with the $\omega_{\rho\sigma}$ constants,
we get the infinitesimal Lorentz transformation
$$
{\Lambda^\mu}_\nu \approx {\delta^\mu}_\nu + 
\frac{1}{2}\omega_{\rho\sigma} {(M^{\rho\sigma})^\mu}_\nu
$$
which, for finite transformations, becomes
$$
\Lambda = \exp\left(\frac{1}{2}\omega_{\rho\sigma}M^{\rho\sigma}\right).
$$
Here, $\omega_{\rho\sigma}$ are a set of constants (the matrix behavior of 
${\omega^\mu}_\nu$ has been extracted to the ${(M^{\rho\sigma})^\mu}_\nu$ now) which tell
us what kind of Lorentz transformation we're applying with $\Lambda$. The
$M^{\rho\sigma}$ matrices are known as the *generators* of the Lorentz 
transformations. 

As an example of how this plays out, a boost in the $x$-direction has 
$\omega_{10} = -\omega_{01} = \chi = \tanh^{-1}(\beta)$, with $\beta = v/c$ and
$\chi$ being the **rapidity**, a relativistic quantity derived from the speed.
In fact, it's not hard to show that 
$$
\cosh(\chi) = \gamma, \qquad \sinh(\chi) = \gamma\beta.
$$
The corresponding $M$ matrix is
$$
{(M^{01})^\mu}_\nu = -{(M^{10})^\mu}_\nu =
\begin{pmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix}
$$
Summing the terms and exponentiating results in
$$
\begin{aligned}
\Lambda &= \cosh(\chi)
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix} -
\sinh(\chi)
\begin{pmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix} + 
\begin{pmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix} \\[8pt] &=
\begin{pmatrix}
\cosh(\chi) & -\sinh(\chi) & 0 & 0 \\
-\sinh(\chi) & \cosh(\chi) & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}
\end{aligned}
$$
which (with a little substitution) matches matrix at the top of the page.
Below is some code that demonstrates this.

In [1]:
# Imports
import numpy as np
from scipy import linalg

In [2]:
m_01 = np.diag([1, 1], k=-2)[::-1, :]
print(r'${M^{01}^\mu}_\nu$ = ')
print(m_01)
print('\n')

# Use beta parameter of sqrt(3/4), as this gives a gamma of 2 for easy
# verification.
beta = 3**.5 / 2
print(f'$beta = {beta}$')
print(f'$\\gamma = {(1-beta**2)**-.5}$')
print(f'$\\gamma\\beta = {beta*(1-beta**2)**-.5}$' + '\n')
chi = np.arctanh(beta)
print(r'${\Lambda^\mu}_\nu$ = ')
# The extra factor of two below comes from summing omega_10 M^10 + omega_01 M^10
print(linalg.expm(-2 * 1/2 * chi * m_01))

${M^{01}^\mu}_\nu$ = 
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


$beta = 0.8660254037844386$
$\gamma = 1.9999999999999996$
$\gamma\beta = 1.7320508075688767$

${\Lambda^\mu}_\nu$ = 
[[ 2.         -1.73205081  0.          0.        ]
 [-1.73205081  2.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


Now, we want to take this infinitesimal form of $\Lambda$ and use it to find a 
relation for $S$. Mimicking the exponential form of $\Lambda$, we'll write
$$
S = \exp\left(\frac{1}{2} \omega_{\rho\sigma} S^{\rho\sigma}\right),
$$
where $S^{\rho\sigma}$ are a collection of six $4\times 4$ matrices to be
determined in a similar manner to the $M^{\rho\sigma}$. Note that we're using
the same $\omega_{\rho\sigma}$ in the formulation of $S$ to ensure that we're
applying the same Lorentz transformation to $\psi$. For infinitesimal
transformations,
$$
S \approx I_4 + \frac{1}{2}\omega_{\rho\sigma} S^{\rho\sigma},
$$
which implies
$$
S^{-1} \approx I_4 - \frac{1}{2}\omega_{\rho\sigma} S^{\rho\sigma},
$$
where $I_4$ is the $4\times 4$ identity matrix. The relationship with the gamma
matrices now reads
$$
\left(I_4 - \frac{1}{2}\omega_{\rho\sigma} S^{\rho\sigma}\right) 
\gamma^\mu
\left(I_4 + \frac{1}{2}\omega_{\rho\sigma} S^{\rho\sigma}\right) = 
\frac{1}{2}\left({\delta^\mu}_\nu + \frac{1}{2}\omega_{\rho\sigma} 
{(M^{\rho\sigma})^\mu}_\nu\right)
\gamma^\nu.
$$
Looking at terms linear in $\omega_{\rho\sigma}$ on each side and equating 
them yields
$$
(\gamma^\mu S^{\rho\sigma} - S^{\rho\sigma}\gamma^\mu) =
 {(M^{\rho\sigma})^\mu}_\nu\gamma^\nu = 
 (\eta^{\mu\rho}{\delta^\sigma}_\nu - \eta^{\mu\sigma}{\delta^\rho}_\nu)
\gamma^\nu
$$
Defining the commutator of two matrices to be $[A, B] = AB - BA$,
$$
[\gamma^\mu, S^{\rho\sigma}] = \eta^{\mu\rho}\gamma^\sigma - \eta^{\mu\sigma}\gamma^\rho.
$$
At this point, all we need to do is find a set of $4\times 4$ matrices
labeled by antisymmetric index pairs $\rho\sigma$. Since the only $4\times 4$
matrices we have to work with are the $\gamma^\mu$ matrices, it's not a big
leap to consider the ansatz
$$
S^{\mu\nu} = a(\gamma^\mu\gamma^\nu - \gamma^\mu\gamma^\nu) =
\begin{cases}
2a\gamma^\mu\gamma^\nu, & \mu \ne \nu \\ 
0, & \mu = \nu
\end{cases}
$$
where $a$ is some to-be-determined constant. Taking the commutator of the
$\gamma^\mu$ with this ansatz gives us
$$
\begin{aligned}
[\gamma^\mu, S^{\rho\sigma}] &= 2a(\gamma^\mu\gamma^\rho\gamma^\sigma - 
\gamma^\rho\gamma^\sigma\gamma^\mu) \\[8pt]
& = 2a (\gamma^\mu\gamma^\rho\gamma^\sigma + \gamma^\rho\gamma^\mu\gamma^\sigma - 
\gamma^\rho\gamma^\mu\gamma^\sigma - \gamma^\rho\gamma^\sigma\gamma^\mu) \\[8pt]
& = 2a (\{\gamma^\mu, \gamma^\rho\} \gamma^\sigma - 
\gamma^\rho\{\gamma^\mu, \gamma^\sigma\}) \\[8pt]
& = 4a(\eta^{\mu\rho}\gamma^\sigma - \eta^{\mu\sigma}\gamma^\rho)
\end{aligned}
$$
In order for our ansatz to match the commutation relation, we need $a = 1/4$.
Therefore,
$$
S^{\mu\nu} = \frac{1}{4}[\gamma^\mu, \gamma^\nu]
= \frac{1}{2}(\gamma^\mu\gamma^\nu - \eta^{\mu\nu}) =
\begin{cases}
\frac{1}{2}\gamma^\mu\gamma^\nu & \mu\ne\nu \\[8pt]
0 & \mu = \nu
\end{cases}
$$
Sometimes, these matrices are scaled and rechristened
$$
\sigma^{\mu\nu} = \frac{i}{2} [\gamma^\mu, \gamma^\nu],
$$
but I will continue to use $S^{\mu\nu}$ to avoid confusion with using $\sigma$
as an index. As we can now see, the $S^{\mu\nu}$ are not the same as the 
$M^{\mu\nu}$, thus the transformation matrix for Dirac spinors, while related
via the $\omega_{\mu\nu}$, is not the same as the transformation for 
four-vectors. The $S^{\mu\nu}$ are known as the generators of the Lorentz
transformations in the *spinor representation*.

The $S$ matrix is thus constructed as
$$
S = \exp\left(\frac{1}{4} \omega_{\rho\sigma}\gamma^\rho\gamma^\sigma\right).
$$
For a boost in the 
$r^1 = x$ direction,
$$
S^{01} = -S^{10} =
\begin{pmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0
\end{pmatrix}
$$
with the $S$ matrix taking the form
$$
S = I_4\cosh\left(\dfrac{\chi}{2}\right) - 
\gamma^0\gamma^1\sinh\left(\dfrac{\chi}{2}\right) =
\begin{pmatrix}
a_+ & 0 & 0 & -a_- \\
0 & a_+ & -a_- & 0 \\
0 & -a_- & a_+ & 0 \\
-a_- & 0 & 0 & a_+
\end{pmatrix}
$$
where
$$
a_\pm = \sqrt{\frac{\gamma \pm 1}{2}}.
$$
For a boost in the general $\boldsymbol{\hat{\rm n}}$ direction, the $S$ matrix
takes the form
$$
S_{\rm boost} = I_4\cosh\left(\dfrac{\chi}{2}\right) - 
\gamma^0 (\boldsymbol{\gamma} \cdot \boldsymbol{\hat{\rm n}})
\sinh\left(\dfrac{\chi}{2}\right)
$$
A calculation of the transformation for $x$-direction boosts is carried out
below.

In [3]:
gamma_0 = np.diag([1, 1, -1, -1])
gamma_1 = np.diag([-1, -1, 1, 1])[::-1, :]
s_01 = .5 * gamma_0 @ gamma_1
# Remember that omega_10 = -omega_01 = chi, hence the minus sign
print(linalg.expm(-2 * 1/2 * chi * s_01))

[[ 1.22474487  0.          0.         -0.70710678]
 [ 0.          1.22474487 -0.70710678  0.        ]
 [ 0.         -0.70710678  1.22474487  0.        ]
 [-0.70710678  0.          0.          1.22474487]]


Note that $S$ is not, in general, unitary. Taking the hermitian conjugate,
$$
S^\dagger = \exp\left(
\frac{1}{4}\omega_{\rho\sigma}(\gamma^\rho\gamma^\sigma)^\dagger
\right)
= \exp\left(
\frac{1}{4}\omega_{\rho\sigma}(\gamma^\sigma)^\dagger(\gamma^\rho)^\dagger
\right)
$$
In our chosen basis, $\gamma^0$ is hermitian and $\gamma^i$ are antihermitian.
Using the anticommutation relations, we can combine these facts to obtain
$$
(\gamma^\mu)^\dagger = \gamma^0 \gamma^\mu \gamma^0.
$$
Then,
$$
S^\dagger = \exp\left(
\frac{1}{4}\omega_{\rho\sigma}\gamma^0 \gamma^\sigma \gamma^\rho \gamma^0
\right)
= \exp\left(
-\frac{1}{4}\omega_{\rho\sigma}\gamma^0 \gamma^\rho \gamma^\sigma \gamma^0
\right)
$$
By expanding this as a Taylor series, we can see that
$$
S^\dagger = \gamma^0 S^{-1} \gamma^0
$$
This means that $S$ is unitary for rotations $(S^{ij} = \gamma^i\gamma^j/2)$
but not for boosts. For rotations by an angle $\phi$ about an arbitrary axis,
$S$ takes the form
$$
S_{\rm rot} = I_4\cos\left(\frac{\phi}{2}\right) +
i (\boldsymbol{\Sigma} \cdot \boldsymbol{\hat{\rm n}})\sin\left(\frac{\phi}{2}\right)
$$
where
$$
\boldsymbol{\Sigma} =
\begin{pmatrix}
\boldsymbol{\sigma} & 0 \\
0 & \boldsymbol{\sigma} \\
\end{pmatrix}
$$
is the (dimensionless) spin operator. If we rotate a spinor about the 
$r^3 = z$ axis by an angle $\omega_{21} = -\omega_{12} = \phi$ then,
$$
S^{12} = \frac{1}{2}\gamma^1\gamma^2 = -\frac{i}{2} \Sigma^3
$$
and
$$
S = 
\begin{pmatrix}
e^{i\phi \sigma^3/2} & 0 \\
0 & e^{i\phi\sigma^3/2}
\end{pmatrix}
= \operatorname{diag}(e^{i\phi/2}, e^{-i\phi/2}, e^{i\phi/2}, e^{-i\phi/2}).
$$
For a rotation by one full turn, $\phi = \tau$, and we get $S = - I_4$. So
rotating a spinor one full turn causes it to pick up a 180° phase shift. This
is not what happens with a four-vector, as the math below shows that 
${\Lambda^\mu}_\nu = {\delta^\mu}_\nu$.

In [4]:
s_12 = -1j / 2 * np.diag([1, -1, 1, -1])
m_12 = np.diag([0, 1, -1, 0])[::-1, :]
phi = np.math.tau
print('S = ') # = -I_4 within machine rounding
print(linalg.expm(-2 * 1/2 * phi * s_12))
print('\n')
print('\Lambda = ') # = delta^\mu_\nu within machine rounding
print(linalg.expm(-2 * 1/2 * phi * m_12))

S = 
[[-1.+1.2246468e-16j  0.+0.0000000e+00j  0.+0.0000000e+00j
   0.+0.0000000e+00j]
 [ 0.+0.0000000e+00j -1.-1.2246468e-16j  0.+0.0000000e+00j
   0.+0.0000000e+00j]
 [ 0.+0.0000000e+00j  0.+0.0000000e+00j -1.+1.2246468e-16j
   0.+0.0000000e+00j]
 [ 0.+0.0000000e+00j  0.+0.0000000e+00j  0.+0.0000000e+00j
  -1.-1.2246468e-16j]]


\Lambda = 
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -3.05390209e-16  0.00000000e+00]
 [ 0.00000000e+00  3.05390209e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Bilinear Invariants
Now that we have determined $S$ and its inverse, we can create quantities
from the bispinor object $\psi$ that are Lorentz invariant. Since a Lorentz
transformation changes $\psi$ according to
$$
\psi \to S\psi
$$
its hermitian conjugate transforms as
$$
\psi^\dagger \to \psi^\dagger S^\dagger.
$$
What we'd like is an object that transforms so that we get an $S^{-1}$ on the
right hand side that will cancel the $S$ that comes from transforming $\psi$.
Since $S^{-1} = \gamma^0 S^\dagger \gamma^0$, we see that the quantity
$\psi^\dagger\gamma^0$ transforms as
$$
\psi^\dagger\gamma^0 \to \psi^\dagger S^\dagger\gamma^0
= \psi^\dagger \gamma^0 \gamma^0 S^\dagger\gamma^0
= \psi^\dagger \gamma^0 S^{-1}.
$$
Defining $\bar\psi = \psi^\dagger\gamma^0$ as the *Dirac adjoint*, we find that
the quantity $\bar{\psi}\psi$ is Lorentz invariant:
$$
\bar{\psi}\psi \to \bar{\psi}S^{-1} S\psi = \bar{\psi}\psi
$$
Note that the Dirac adjoint obeys the *adjoint equation*
$$
i\hbar\partial_\mu\bar\psi \gamma^\mu + mc\bar\psi = 0.
$$
This object is in fact the basis for all the Lorentz invariant quantities we
can form from a bispinor. For instance, if we consider the object
$\bar{\psi}\gamma^\mu\psi$, we find that
$$
\bar{\psi}\gamma^\mu\psi \to \bar{\psi}S^{-1}\gamma^\mu S\psi
= {\Lambda^\mu}_\nu \bar{\psi}\gamma^\nu\psi,
$$
which is the transformation rule for a four-vector! All told, there are five
bilinear Lorentz invariant objects we can construct:
$$
\left\{
\begin{array}{lll}
(1) & \bar\psi\psi & \text{scalar} \\
(2) & \bar\psi\gamma^5\psi & \text{pseudoscalar} \\
(3) & \bar\psi\gamma^\mu\psi & \text{vector} \\
(4) & \bar\psi\gamma^\mu\gamma^5\psi & \text{pseudovector} \\
(5) & \bar\psi S^{\mu\nu}\psi & \text{antisymmetric tensor}
\end{array}
\right\}
$$
where
$$
\gamma^5 \equiv i\gamma^0\gamma^1\gamma^2\gamma^3 =
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}.
$$
What's rather remarkable about these quantities is that you can tell at a
glance what kind of object each invariant is, despite the fact that the indices
for $\gamma^\mu$ are not four-vector components – they are an index that tells
you which of four matrices to pick – and yet when sandwiched between $\bar\psi$
and $\psi$ end up being the tensor your gut tells you they are.